### ISSUE TITLE
Potential bug when creating image crops

### ISSUE THREAD

**Issue by ManicMunchkin** [HaojHuang/Equivariant-Transporter-Net#5]
Hi,
first off I want to thank you for publishing an actually working codebase and well documented project. 
I am using Eq-Transporter Nets in my Master Thesis and when looking through the code in the Attention and Transport modules I noticed a potential bug when crops are taken from the input images.

e.g. Line 121 from the attention module: `crop = input_tensor[:,:,p[0]:(p[0] + self.crop_size),p[1]:(p[1] + self.crop_size)]`
or Line 89 from the transport module: `crop = crop[:, :, p[0]:(p[0] + self.crop_size_1), p[1]:(p[1] + self.crop_size_1)]`

Wouldn't this put the upper left corner of the crop window at the given location instead of centering the crop window at the location?
I would expect the crop to be made like this: 
`crop = input_tensor[:,:,(p[0]-crop_size/2):(p[0]+crop_size/2),(p[1]-crop_size/2):(p[1]+crop_size/2)]`
So that it is centered at the pick location.

Is this an actual bug or am I just missing something here?

**Comment by HaojHuang** [comment]
Hi, the image was padded.

**Comment by ManicMunchkin** [comment]
Hi, 
true, however it is padded by crop_size/2 in every direction (up, left, down, right) in the Attention and the Transport network.
e.g. 
```
self.pad_size_1 = int(self.crop_size_1 / 2)
self.padding_1 = np.zeros((3, 2), dtype=int)
self.padding_1[:2, :] = self.pad_size_1
```
Which actually illustrates my point, because padding by crop_size/2 would make sense if the crop is centered around p, since then the maximum overlap over the input image boundaries would be crop_size/2. This would be figure B in the following drawing.

Figure A shows the way cropping is implemented as I understood it, which could lead to overlap over the padded area.
Figure B shows the cropping centered around the pixel p.
![image](https://github.com/HaojHuang/Equivariant-Transporter-Net/assets/45815558/e9a4f330-fb9d-4948-ab57-e762b589da1d)

**Comment by HaojHuang** [comment]
Hi,

The coordinate of P changes after padding since the reference frame changed. For example, the coordinate of the upper left corner of the original image is (0,0) and after padding with 10 pixels on the four sides of the image, the coordinate of the upper left corner of the *original image* is (10, 10) instead of (0,0).

**Comment by ManicMunchkin** [comment]
Aah that makes sense. 
Thanks for the explanation!
